USE [CBS]
GO

/****** Object:  Table [dbo].[HouseholdOutput]    Script Date: 2/6/2022 8:27:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HouseholdOutput](
	[I_HH_ID] [int] NOT NULL,
	[LAAG_INK] [int] NULL,
	[ARMLAG] [int] NULL,
	[ARMLAGKL1] [int] NULL,
	[BMNORMH] [int] NULL,
	[ARMSOC] [int] NULL,
	[ARMSOCKL1] [int] NULL,
 CONSTRAINT [PK_HouseholdOutput] PRIMARY KEY CLUSTERED 
(
	[I_HH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

