USE [CBS]
GO

/****** Object:  Table [dbo].[Household_FULL]    Script Date: 2/6/2022 8:26:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Household_FULL](
	[I_HH_ID] [int] NOT NULL,
	[BESTINKH] [decimal](10, 2) NULL,
	[EQUI] [decimal](10, 2) NULL,
	[POP] [int] NULL,
	[SAMHH] [int] NULL,
 CONSTRAINT [PK_Household_FULL] PRIMARY KEY CLUSTERED 
(
	[I_HH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

