USE [CBS]
GO

/****** Object:  Table [dbo].[Link_Table_FULL]    Script Date: 2/6/2022 8:27:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Link_Table_FULL](
	[I_SOFINR] [nvarchar](50) NOT NULL,
	[I_HH_ID] [int] NULL,
	[PAAR_NR] [int] NULL,
 CONSTRAINT [PK_Link_Table_FULL] PRIMARY KEY CLUSTERED 
(
	[I_SOFINR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

